"""Add Comment

Revision ID: 75100cea0323
Revises: 416e2f0599ec
Create Date: 2026-01-23 14:16:02.716977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75100cea0323'
down_revision = '416e2f0599ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=250), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todo_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
